### ISSUE TITLE
Known bugs

### ISSUE THREAD

**Issue by ZekNikZ** [AshleyLuEllen/AttendanceReportGenerator#1]
- [x] Having no override files specified seems to be a problem (also check if this is the case for no attendance files
- [x] Putting a file that doesn't exist into the overrides file seems to ignore it with no error message (is that intended?)
- [x] Non-qualifier file does not have a header row
- [x] Ability to put all generated reports in a separate folder instead of the working directory

**Comment by AshleyLuEllen** [comment]
All have been solved, and code has been refactored some.
