### ISSUE TITLE
More bugs

### ISSUE THREAD

**Issue by ZekNikZ** [AshleyLuEllen/AttendanceReportGenerator#2]
- [x] If `reports` directory is missing, program throws error
- [x] If roster is not present, bad things happen
- [x] If error is thrown, please stop execution of program or generation of current report appropriately.

**Comment by AshleyLuEllen** [comment]
These bugs are now squashed. It prints one error saying that the roster file could not be found and does not try to create master files or stats covering more than one session.
If a file is listed in input and has an opening, there is an error printed saying the file could not be opened and continues ignoring the session.

**Comment by AshleyLuEllen** [comment]
reports should throw an error if the file is missing, but the error has now been changed. The parameter is now required so if it is not present it throws an error.
